name: Build Test App

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Npm Install
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PKG_TOKEN }}" > ~/.npmrc
          npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
            name: OpenBlock-Desktop-Distro-win-ia32
            path: dist/OpenBlock-Desktop-Distro*ia32.exe
            retention-days: 1

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenBlock-Desktop-Distro-win-x64
          path: dist/OpenBlock-Desktop-Distro*x64.exe
          retention-days: 1

  build-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install python2.7
        run: |
          brew install pyenv
          pyenv install 2.7.18
          pyenv global 2.7.18

      - name: Npm Install
        run: |
          pip install setuptools
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PKG_TOKEN }}" > ~/.npmrc
          npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
          USE_HARD_LINKS: false # To fix err in https://github.com/electron-userland/electron-builder/issues/3179
        run: |
          export PYTHON_PATH=$(pyenv root)/shims/python
          npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenBlock-Desktop-Distro-darwin
          path: dist/OpenBlock-Desktop-Distro*.dmg
          retention-days: 1

  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Npm Install
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PKG_TOKEN }}" > ~/.npmrc
          npm ci

      - name: Fix chrome-sandbox permissions
        run: |
          sudo chown root:root node_modules/electron/dist/chrome-sandbox
          sudo chmod 4755 node_modules/electron/dist/chrome-sandbox

      - name: Patch electron-builder-wrapper.js
        # Due to some unknown reasons, the packaging operation will report
        # an error when it is successful on the Linux CI. We need to ignore
        # the error here and let CI continue.
        # https://github.com/electron-userland/electron-builder/issues/8456
        run: |
          sed -i '/if\s*(\s*result\.status\s*)\s*{/a\
          \ \ \ \ if (target.platform === '\''linux'\'' && result.status === 1) {\n\
          \ \ \ \ \ \ \ \ return; // ignore error on linux\n\
          \ \ \ \ }
          ' scripts/electron-builder-wrapper.js

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
          USE_HARD_LINKS: false
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenBlock-Desktop-Distro-linux
          path: dist/OpenBlock-Desktop-Distro*.deb
          retention-days: 1
