name: Build Test App

on:
  push:
    tags:
      - 'vkada*'
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: blocks Install
        uses: actions/checkout@v2
        with: 
          repository: openblockee/openblock-ee-blocks
          ref: refs/heads/main
          token: ${{ secrets.GH_TOKEN }}
          path: openblock-blocks
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x' 
          architecture: 'x64'
      - run: |
          cd openblock-blocks
          npm ci
          npm link

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
          architecture: 'x64'

      - name: link Install
        uses: actions/checkout@v2
        with: 
          repository: openblockee/openblock-ee-link
          ref: refs/heads/develop
          token: ${{ secrets.GH_TOKEN }}
          path: openblock-link
      - run: |
          cd openblock-link
          npm ci
          npm link

      - name: resource Install
        uses: actions/checkout@v2
        with: 
          repository: openblockcc/openblock-resource
          ref: refs/heads/main
          token: ${{ secrets.GH_TOKEN }}
          path: openblock-resource
      - run: |
          cd openblock-resource
          npm ci
          npm link

      - name: vm Install
        uses: actions/checkout@v2
        with: 
          repository: openblockee/openblock-ee-vm
          ref: refs/heads/kada
          token: ${{ secrets.GH_TOKEN }}
          path: openblock-vm  
      - run: |
          cd openblock-vm
          npm ci
          npm link

      - name: l10n Install
        uses: actions/checkout@v2
        with: 
          repository: openblockee/openblock-ee-l10n
          ref: refs/heads/kada
          token: ${{ secrets.GH_TOKEN }}
          path: openblock-l10n  
      - run: |
          cd openblock-l10n
          npm ci
          npm run build
          npm link --force

      - name: gui Install
        uses: actions/checkout@v2
        with: 
          repository: openblockee/openblock-ee-gui
          ref: refs/heads/kada-desktop
          token: ${{ secrets.GH_TOKEN }}
          path: openblock-gui  
      - run: |
          cd openblock-gui
          npm ci
          npm install --save-dev encoding@^0.1.13 iconv browser
          npm link
          npm link openblock-vm openblock-blocks openblock-l10n

      - name: desktop Install
        uses: actions/checkout@v2
        with: 
          repository: openblockee/openblock-ee-desktop
          ref: refs/heads/kada
          token: ${{ secrets.GH_TOKEN }}
          path: openblock-desktop  
      - run: |
          cd openblock-desktop
          npm ci
          npm link openblock-l10n openblock-vm openblock-link openblock-resource openblock-gui openblock-blocks
                   
      - name: Build Dist
        env:
          # GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          cd openblock-desktop
          npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenBlock-Desktop-CaDA.exe
          path: openblock-desktop/dist/OpenBlock-Desktop-CaDA_*.exe
          retention-days: 1

